server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devopsdb_umn6
    username: devopsdb_umn6_user
    password: devopsdb_umn6_user
  jpa:
    hibernate:
      ddl-auto: update

app:
  hosting: Local